#pragma once

#include "RE/H/hkPointerMap.h"
#include "RE/H/hkStringPtr.h"
#include "RE/H/hkbBindable.h"
#include "RE/H/hkbContext.h"
#include "RE/H/hkbEvent.h"

namespace RE
{
	class hkbNodeInternalStateInfo;

	// Stores returned info about a child of a node.
	struct hkbNodeChildInfo
	{
		hkbNodeChildInfo() = default;

		// members
		hkbNode* node{};                 // 00 - The child node template
		bool     ignoreEvents{ false };  // 08 - If true, events will not be sent to the nodes and events generated by the node will not be forwarded
		bool     reset{ false };         // 09 - Whether to reset the node asap (deactivate and then activate)
		bool     syncToParent{ false };  // 0A - Whether or not to synchronize this node with the parent
		bool     stopped{ false };       // 0B - Whether or not the parent wants this child to be moved forward in time
		char     pad0C[4];               // 0C
	};
	static_assert(sizeof(hkbNodeChildInfo) == 0x10);

	class hkbNode : public hkbBindable
	{
	public:
		inline static constexpr auto RTTI = RTTI_hkbNode;
		inline static constexpr auto VTABLE = VTABLE_hkbNode;

		// Flags used when calling GenNumChildren() or GetChildren().
		enum class GetChildrenFlagBits : std::int32_t
		{
			// If true, only return the active children (otherwise, all children).
			kActiveOnly = 1 << 0,

			// If true, only return generators (else also return modifiers).
			kGeneratorsOnly = 1 << 1,

			// If true, the behavior graphs pointed to by hkbBehaviorReferenceGenerators
			// will be ignored (along with all of their descendants).
			kIgnoreReferencedBehaviour = 1 << 2
		};
		using GET_CHILDREN_FLAGS = stl::enumeration<GetChildrenFlagBits, int32_t>;

		enum class CloneState
		{
			kDefault = 0,
			kTemplate = 1,
			kClone = 2,
			kShareable = 3
		};

		hkbNode() { stl::emplace_vtable(this); }
		~hkbNode() override = default;  // 00

		HK_HEAP_REDEFINE_NEW();

		// add
		virtual void                Activate(const hkbContext& a_context);                                                                                                                                       // 04 - { return; }
		virtual void                Update(const hkbContext& a_context, float a_timestep);                                                                                                                       // 05 - { userData |= 1; }
		virtual void                HandleEvent(const hkbContext& a_context, hkbEvent event);                                                                                                                    // 06 - { return; }
		virtual void                Deactivate(const hkbContext& a_context);                                                                                                                                     // 07 - { return; }
		virtual int                 GetMaxNumChildren(stl::enumeration<GetChildrenFlagBits, std::int32_t> flags);                                                                                                // 08 - { return 2; }
		virtual void                GetChildren(stl::enumeration<GetChildrenFlagBits, std::int32_t> flags, hkbNodeChildInfo& childrenInfo);                                                                      // 09 - { return; }
		virtual bool                IsValid(hkStringPtr& err) const;                                                                                                                                             // 0A - { return 1; }
		virtual void                Precompute(const hkbContext& context);                                                                                                                                       // 0B - { return; }
		virtual hkbNode*            CloneNode(hkbBehaviorGraph& rootBehavior) const;                                                                                                                             // 0C
		virtual hkReferencedObject* CreateInternalState();                                                                                                                                                       // 0D - { return 0; }
		virtual void                GetInternalState(hkReferencedObject& internalState) const;                                                                                                                   // 0E - { return; }
		virtual void                GetInternalStateUser(const hkbBehaviorGraph& rootBehavior, hkReferencedObject& internalState);                                                                               // 0F - { return; }
		virtual void                SetInternalState(const hkReferencedObject& internalState);                                                                                                                   // 10 - { return; }
		virtual void                SetInternalStateUser(const hkbContext& context, const hkReferencedObject& internalState, hkPointerMap<int16_t, const hkbNodeInternalStateInfo*>& nodeIdToInternalStateMap);  // 11 - { return; }
		virtual void                GetActiveEvents(hkPointerMap<int, bool>& activeEvents) const;                                                                                                                // 12 - { return; }
		virtual bool                IsTransitionEffect() const;                                                                                                                                                  // 13 - { return 0; }
		virtual void                GetActiveVariablesSpecial(hkPointerMap<int, bool>& activeVariables) const;                                                                                                   // 14 - { return; }
		virtual bool                IsGenerator() const;                                                                                                                                                         // 15 - { return 0; }
		virtual bool                IsBehaviorGraph() const;

		// members
		std::uint64_t                              userData{ 0 };                       // 30
		hkStringPtr                                name;                                // 38
		std::int16_t                               id{ -1 };                            // 40
		stl::enumeration<CloneState, std::uint8_t> cloneState{ CloneState::kDefault };  // 42
		std::uint8_t                               pad43;                               // 43
		std::uint32_t                              pad44;                               // 44
	};
	static_assert(sizeof(hkbNode) == 0x48);
}
